name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repo on the runner
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          architecture: x64
      - name: Build and verify with Maven 
        run: mvn --batch-mode --update-snapshots verify